# Generated by Django 4.0.6 on 2022-08-03 22:18

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('fromDate', models.DateField(default=datetime.datetime(2022, 8, 3, 19, 18, 55, 59488))),
                ('deadlineDate', models.DateField()),
            ],
        ),
    ]
